### ISSUE TITLE
Impact on PyPI Search 

### ISSUE THREAD

**Issue by jonathanbarratt** [benjaoming/pytosquatting#1]
Unless these packages are only temporary until a hardened package manager is the Python norm, could they degrade the quality of PyPI search results, or is there a simple filter that could exclude pytosquats? Not really a problem yet, at least not for me anyway, more just curious what your perspective on it would be.

Thanks for tightening security on my dependencies! ;)

**Comment by benjaoming** [comment]
Hi @jonathanbarratt !

Didn't see your comment before now, and somehow I wasn't watching a repo that I created myself. Same thing happened over on pipsec: https://github.com/benjaoming/pipsec/issues

For clarity, we should distinguish between namesquatting and typosquatting. For the stdlib packages, we squatted everything that wasn't squatted and the PyPI Warehouse project is now building a database-backed Blacklist for admins: https://github.com/pypa/warehouse/pull/2396

So namesquatting issues should be relatively solved now that the stdlib names are taken care off.

I would like to call for someone to have a look at some of the stdlib packages that we didn't squat with pytosquatting. I should get a full list, but here are some:

 * functools
 * token
 * locale

Regarding typosquatting and filtering, this will be the goal of `pipsec`!

Thanks for getting in touch, let me know if there's anything for the website or some additional packages you think we should squat to test them for stats.
